[supervisord]
nodaemon = true
logfile = /data/logs/supervisord.log
pidfile = /tmp/supervisord.pid

[program:postgres]
user = postgres
directory = /tmp
command = /usr/lib/postgresql/16/bin/postgres -D /data/pg -p 5432 -h 127.0.0.1 -k /tmp
autorestart = true
stdout_logfile = /data/logs/postgres.log
stderr_logfile = /data/logs/postgres.log

[program:mongo]
command = /opt/mongo/bin/mongod --dbpath /data/mongo --bind_ip 127.0.0.1 --port 27017
autorestart = true
stdout_logfile = /data/logs/mongo.log
stderr_logfile = /data/logs/mongo.log

[program:elasticsearch]
user = es
environment = ES_JAVA_OPTS="-Xms512m -Xmx512m"
directory = /tmp
command = /opt/es/bin/elasticsearch -E path.data=/data/es -E path.logs=/data/eslogs -E cluster.name=ecommerce-single -E node.name=single-1 -E discovery.type=single-node -E xpack.security.enabled=false -E network.host=127.0.0.1 -E http.port=9200
autorestart = true
stdout_logfile = /data/logs/es.log
stderr_logfile = /data/logs/es.log

[program:rabbitmq]
environment = RABBITMQ_NODENAME="rabbit@localhost",RABBITMQ_MNESIA_BASE="/data/rabbit/mnesia",RABBITMQ_LOG_BASE="/data/rabbit/log",RABBITMQ_NODE_IP_ADDRESS="127.0.0.1",RABBITMQ_NODE_PORT="5672",RABBITMQ_PID_FILE="/tmp/rabbit.pid"
command = /usr/sbin/rabbitmq-server
autorestart = true
stdout_logfile = /data/logs/rabbit.log
stderr_logfile = /data/logs/rabbit.log

[program:api]
environment = PG_DSN="postgresql://ecommerce:ecommerce@127.0.0.1:5432/ecommerce",MONGO_DSN="mongodb://127.0.0.1:27017",MONGO_DB_NAME="ecommerce",ES_URL="http://127.0.0.1:9200",RABBITMQ_URL="amqp://guest:guest@127.0.0.1:5672//"
directory = /app
command = java -jar /app/app.jar
autorestart = true
stdout_logfile = /data/logs/api.log
stderr_logfile = /data/logs/api.log

[program:nginx]
command = /usr/sbin/nginx -g "daemon off;"
autorestart = true
stdout_logfile = /data/logs/nginx.log
stderr_logfile = /data/logs/nginx.log
